networks:
  proxy:
    name: backbone_proxy
    external: true
  monitoring:
    name: backbone_monitoring
    external: true

secrets:
  admin_password:
    environment: ADMIN_PASSWORD

services:
  grafana:
    image: grafana/grafana-oss:11.5.2
    container_name: grafana
    user: "9003:9003"
    labels:
      - traefik.enable=true
      - traefik.docker.network=backbone_proxy
      - traefik.http.routers.grafana.ruleSyntax=v3
      - traefik.http.routers.grafana.tls=true
      - traefik.http.routers.grafana.tls.certresolver=${CERTRESOLVER:-}
      - traefik.http.routers.grafana.entryPoints=https
      - traefik.http.routers.grafana.rule=Host("${APPLICATION_FQDN}")
      - traefik.http.routers.grafana.service=grafana-service
      - traefik.http.services.grafana-service.loadbalancer.server.port=3000
    environment:
      TZ: Europe/Berlin
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: false
      GF_SECURITY_ADMIN_PASSWORD__FILE: "/run/secrets/admin_password"
      GF_SECURITY_COOKIE_SECURE: true
      GF_SECURITY_COOKIE_SAMESITE: strict
      GF_SECURITY_STRICT_TRANSPORT_SECURITY: true
      GF_SERVER_DOMAIN: "${APPLICATION_FQDN}"
      GF_SERVER_ROOT_URL: "https://${APPLICATION_FQDN}"
      GF_USERS_ALLOW_ORG_CREATE: false
    volumes:
      - "./grafana:/var/lib/grafana"
      - "./provisioning:/etc/grafana/provisioning"
      - "./providers/dashboards:/etc/dashboards"
    secrets:
      - source: admin_password
        uid: "9003"
        gid: "9003"
    restart: unless-stopped
    networks:
      - proxy
      - monitoring
